name: flex_list
description: A Flutter layout widget for flexible lists. It behaves as you would expect Expand widgets to behave within a wrap.
version: 1.2.0
homepage: https://github.com/Jozott00/flex_list

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
